---
title: "Untitled"
author: "Lipidong"
date: "2015年6月8日"
output: word_document
---

## Linux 命令学习

### ls -alh
>  a 列出当前目录下所有文件，包含(. .. 隐藏文件)<br/>
   l 显示详细信息<br/>
   h 显示文本大小（human read）<br/>

### 文件权限
10个长度分成4段： 
                
    1段1个字符：- 普通文件； d 文件夹； l 符号链接（相当于windows里的快捷键)
    2段3个字符：表示文件拥有者对文件的权限 r 读（4）， w 写（2）， x 执行（1）
    3段3个字符：表示文件拥有者同一组中的用户对文件的权限  r 读（4）， w 写（2）， x 执行（1）
    4段3个字符：表示其他用户对文件的权限 r 读（4）， w 写（2）， x 执行（1）


### cd 绝对路径/相对路径
> cd .. 回到上级目录 <br/>
  cd - 回到之前的一个目录<br/>
  cd ~ 回到用户目录<br/>

### pwd
显示当前目录

### cat less more head tail
> cat 显示全部文件， cat -n 文件名 同时显示行号<br/>
  more 分页显示，可以向下翻页浏览，不能向上浏览<br/>
  less 分页浏览， 既可以向上也可以向下浏览<br/> (按键 f 空格 pagedown 向下翻页， b pageup 向上翻页, / 查找， q 退出)
  head 文档前几行<br/>
  tail 文档后几行<br/>

### grep pattern filepath 显示匹配的行
> pattern 正则表达式 
> filepath 文件路径
可以通过管道符（|）与其他命令合用来筛选需要的内容
> ls -al | grep ^d 显示当前目录下的文件夹

### find 
> find 搜索路径 -name 搜索的文件名称
> find 搜索路径 -regex “正则表达式”

### ps -ef
显示所有进程，包含PID（第二列）

### kill -9 PID
根据PID， 强制杀死进程

### cp -r 源文件 目标文件
> -r 复制文件夹中的文件

复制文件

### mv -r 源文件 目标文件

移动文件
> -r 移动文件夹中的文件

### rm -rf 文件路径
删除文件
> -r 删除文件夹中的文件
> -f 强制删除

### ln -s 源文件 连接文件
类似于windows下的快捷方式

### awk 了解 
读取文件，并对文件进行列操作，比如：
> awk '{print $1, $4}' netstat.txt
> 显示 netstat.txt 文件的第1列和第4列

### sed 了解
 读取文件，并对文件进行行操作，比如

> sed "s/my/Hao Chen's/g" pets.txt
> 将 pets.txt 文件中的 my 替换为 Hao Chen's

### chmod 744 文件路径
修改文件的权限，744表示 rwxrw_rw_




